### ISSUE TITLE
Start streaming listener fails

### ISSUE THREAD

**Issue by hbokh** [robertbarabas/ansible-tutorial#1]
Looks like a great tutorial on MySQL HA or master/slave!
However, the playbook fails with this error:

```
TASK [Start streaming listener] ************************************************
fatal: [192.168.10.101]: FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: No JSON object could be decoded"}
```

**Comment by hbokh** [comment]
Managed to fix it like this in `plays/clone_mysql.yml`.  
Add `ignore_errors: true` and a socket-option for `innobackupex`:

```
[ ... cut ... 8< ... cut ...]

    - name: Start streaming listener
      shell: "cd {{ datadir }} && nc -l {{ port }} | xbstream -xv ."
      async: 300
      poll: 0
      ignore_errors: True

- name: Source
  vars:
    - datadir: /var/lib/mysql
    - port: 9999
    - source: master
    - target: slave
    - owner: mysql
    - group: mysql
  hosts:
    - "{{ source }}"
  tasks:
    - name: Setup replication user
      shell: mysql -e "GRANT REPLICATION SLAVE ON *.* TO 'replication'@'%' IDENTIFIED BY 'dummysecret';"

    - name: Stream backup
      shell: innobackupex --socket=/var/lib/mysql/mysql.sock --stream xbstream /tmp | nc {{ target }} 9999
```
